### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by MYSK-QC** [0mar99/kernel_xiaomi_sm8350#1]
Compilation error on the reborn-14-new branch.
The error message is as follows.

drivers/soc/qcom/icnss2/qmi.o: In function `icnss_get_bdf_file_name':
/root/qc/out/../drivers/soc/qcom/icnss2/qmi.c:945: undefined reference to `get_hw_version_platform'
/root/qc/out/../drivers/soc/qcom/icnss2/qmi.c:946: undefined reference to `get_hw_country_version'
drivers/net/wireless/cnss2/qmi.o: In function `cnss_get_bdf_file_name':
/root/qc/out/../drivers/net/wireless/cnss2/qmi.c:547: undefined reference to `get_hw_country_version'
/root/qc/out/../drivers/net/wireless/cnss2/qmi.c:548: undefined reference to `get_hw_version_platform'
/root/qc/out/../drivers/net/wireless/cnss2/qmi.c:549: undefined reference to `get_hw_version_build'
/root/qc/out/../drivers/net/wireless/cnss2/qmi.c:550: undefined reference to `get_hw_version_major'
/root/qc/out/../drivers/net/wireless/cnss2/qmi.c:551: undefined reference to `get_hw_version_minor'
make[1]: *** [/root/qc/Makefile:1193：vmlinux] 错误 1
make[1]: 离开目录“/root/qc/out”
make: *** [Makefile:183：sub-make] 错误 2![Screenshot_2023-11-03-17-39-08-535_com.sonelli.juicessh.jpg](https://github.com/0mar99/kernel_xiaomi_sm8350/assets/68981944/184927b0-a71d-43bc-91cf-b38fd2071fe2)

**Comment by chemusqui1** [comment]
Hello, check if Mi HWID driver is being built, as these symbols are dependent of it, needed for identifying device model and region for loading WLAN and Modem configurations inside NON_HLOS image (as Ximi itself ships all region and models fw images inside same modem image, like venus or lisa ones)
